### ISSUE TITLE
Collapse companies on news when there are more than 4 companies mentioned....

### ISSUE THREAD

**Issue by benmilesabraham** [iqblade/mobile-app-issues#11]
When there are more than 4 companies mentioned on a news story I think we need to show the first 4 or so with an elipsis and then a reference to '9 more companies tagged - see more' type reference.

for example to stop this:

![image from ios 7](https://user-images.githubusercontent.com/40032148/53984401-20ad7980-4111-11e9-97ca-fea5348f8783.png)

**Comment by sean-newby** [comment]
We are looking to swap the narrative and the tags around so the tags are on the bottom and the "Show full article" button is below the narrative but above the tags. This means it doesn't matter how many tags there are you can still see the narrative and the  button.

**Comment by sean-newby** [comment]
Done and in next build
