### ISSUE TITLE
Can't click on company name from news article.

### ISSUE THREAD

**Issue by benmilesabraham** [iqblade/mobile-app-issues#3]
I would expect to be able to click on the company names tagged in a news story and be taken to their company profile (but they aren't active links to companies).

**Comment by benmilesabraham** [comment]
![image from ios](https://user-images.githubusercontent.com/40032148/53968787-930d6200-40ef-11e9-9be3-f47e1cd2a20f.png)

**Comment by sean-newby** [comment]
HI @benmilesabraham The company number is returned for those tags so we will be able to open the company profile from there.
