### ISSUE TITLE
Can't navigate to this company on the mobile app.

### ISSUE THREAD

**Issue by benmilesabraham** [iqblade/mobile-app-issues#6]
08240765

It just comes up with an error. When I try to click on company (Firesprite Limited) it just returns an error and says to contact IQBlade. It gives me the option to Refresh but when I click that it just takes me to the Home Page?

The company has a full profile and can be viewed from the Web App?

**Comment by benmilesabraham** [comment]
![image from ios 2](https://user-images.githubusercontent.com/40032148/53975036-e4bbe980-40fb-11e9-87b0-c261ad5105e9.png)

**Comment by benmilesabraham** [comment]
![image from ios 3](https://user-images.githubusercontent.com/40032148/53975149-1634b500-40fc-11e9-99e0-d9fd6c44fd75.png)

**Comment by aranw** [comment]
I'm going to close this and transfer it to our internal repo as this is a problem our end and not within the app.
